// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADY0FwZ-K4lOP0fReDp4hIEjZHPrKRvMQ',
    appId: '1:211924880437:web:0918cc8f7fcc1ed73e357c',
    messagingSenderId: '211924880437',
    projectId: 'fir-push-notification-f9329',
    authDomain: 'fir-push-notification-f9329.firebaseapp.com',
    storageBucket: 'fir-push-notification-f9329.appspot.com',
    measurementId: 'G-W6FD4P2P93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM6c0VuXlfdHh--13Jsbz21PYwzx43TUE',
    appId: '1:211924880437:android:f0224342b06c25693e357c',
    messagingSenderId: '211924880437',
    projectId: 'fir-push-notification-f9329',
    storageBucket: 'fir-push-notification-f9329.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKRafdpPE4o9eI6VMKVU37aW5f5naI_Bo',
    appId: '1:211924880437:ios:737b7b26ac2998663e357c',
    messagingSenderId: '211924880437',
    projectId: 'fir-push-notification-f9329',
    storageBucket: 'fir-push-notification-f9329.appspot.com',
    iosBundleId: 'com.example.firebasePushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKRafdpPE4o9eI6VMKVU37aW5f5naI_Bo',
    appId: '1:211924880437:ios:737b7b26ac2998663e357c',
    messagingSenderId: '211924880437',
    projectId: 'fir-push-notification-f9329',
    storageBucket: 'fir-push-notification-f9329.appspot.com',
    iosBundleId: 'com.example.firebasePushNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADY0FwZ-K4lOP0fReDp4hIEjZHPrKRvMQ',
    appId: '1:211924880437:web:b24e8ac6f28efb2c3e357c',
    messagingSenderId: '211924880437',
    projectId: 'fir-push-notification-f9329',
    authDomain: 'fir-push-notification-f9329.firebaseapp.com',
    storageBucket: 'fir-push-notification-f9329.appspot.com',
    measurementId: 'G-0EDNBHE6T8',
  );

}